# Generated by Django 4.1.7 on 2023-03-19 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.TextField()),
                ('production_year', models.DateField()),
                ('volume', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barek.cabinet')),
            ],
        ),
    ]
